name: MYSQL

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-host:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: still present in the next step?
        run: |
          echo ${REPO_LOWERCASE}
